### ISSUE TITLE
Document which variant of bat firmware should be used on ergoCub robot

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-firmware-build#115]
In https://github.com/robotology/icub-firmware-build/tree/v1.37.0/CAN/bat there are `bat.r1` and `bat.icub3`, and I was not able to understand which one should be used on ergoCub. It would be great to document this, thanks in advance!

**Comment by valegagge** [comment]
Since the difference between r1 and icub3 exe is related to the `dcdc_management` phase: in `iCub3` and `ergoCub` the management of the cpu and motors lines is done separately and they can work detached. Differently, in `R1` cpu and boards lines work always together.
Moreover, since `R1` and `iCub` and `ergoCub` work with different battery packs, the voltage thresholds are set differently on the two firmware.

Therefore we renamed `bat.icub3` in bat and leave bat.r1.

Related PRs are:

PRs opened here:
- https://github.com/robotology/icub-firmware-build/pull/120
- https://github.com/robotology/icub-firmware/pull/443
- https://github.com/icub-tech-iit/documentation/pull/329

**Comment by valegagge** [comment]
Request satisfied, doesn't it?

I think we can close this issue.

@traversaro
