### ISSUE TITLE
Add the possibility pass the root of robots-configuration in FirmwareUpdater.script.info.all.sh

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-firmware-build#19]
[`FirmwareUpdater.script.info.all.sh`](https://github.com/robotology/icub-firmware-build/blob/devel/scripts/FirmwareUpdater.script.info.all.sh) searches for `robots-configuration` folder inside `$ROBOT_CODE` i.e. 

```sh
./manageFWrobot.py -n $ROBOT_CODE/robots-configuration/$YARP_ROBOT_NAME/network.$YARP_ROBOT_NAME.xml -f ../info/firmware.info.xml -p all -a info | tee ../logs/log.of.FirmwareUpdater.$YARP_ROBOT_NAME.info.all.txt
```

We usually install `robots-configuration` as part of the superbuild, so our path is `$ROBOTOLOGY_SUPERBUILD_DIR/src/robots-configuration`. It would be nice to pass the root of robots configuration as parameter to the `sh` script.

cc @traversaro @isorrentino

**Comment by traversaro** [comment]
I think the current solution is not ideal for two reason:
*  The location of the file is hardcoded, so we need either to use that the manual ( https://icub-tech-iit.github.io/documentation/sw_installation/linux_from_sources_manual/ ) installation used, or the superbuild one ( https://icub-tech-iit.github.io/documentation/sw_installation/linux_from_sources_superbuild/ )
* The file is loaded from the **source directory**, while typically configuration files are loaded from the installation directory (or the build one if the install is not used)

I think both issues can be avoided if instead of using: 
~~~
./manageFWrobot.py -n $ROBOT_CODE/robots-configuration/$YARP_ROBOT_NAME/network.$YARP_ROBOT_NAME.xml -f ../info/firmware.info.xml -p all -a info | tee ../logs/log.of.FirmwareUpdater.$YARP_ROBOT_NAME.info.all.txt
~~~
we use the [`yarp resource`](http://www.yarp.it/git-master/yarp.html#yarp_resource) utility to find the file, i.e
~~~
./manageFWrobot.py  `yarp resource --from network.$YARP_ROBOT_NAME.xml` -f ../info/firmware.info.xml -p all -a info | tee ../logs/log.of.FirmwareUpdater.$YARP_ROBOT_NAME.info.all.txt
~~~
this will work fine both manual and superbuild installation, and will use the installed version of the files instead of the source one (so it will work even if we switch to use binaries in the future).

**Comment by marcoaccame** [comment]
> ./manageFWrobot.py -n `yarp resource --from network.$YARP_ROBOT_NAME.xml` 

seems a good solution by me.

**Comment by traversaro** [comment]
Given https://github.com/robotology/icub-firmware-build/pull/21, probably we can close this issue @GiulioRomualdi ?

**Comment by GiulioRomualdi** [comment]
Yes!

**Comment by traversaro** [comment]
Note that probably `yarp resource` now also prints `[DEBUG]` message so it is not suitable anymore to do this, but that is another story.
